### ISSUE TITLE
npm run test failed with "Invalid withdraw proof"

### ISSUE THREAD

**Issue by kooy** [tornadocash/tornado-core#103]
I've been trying to run ./cli.js test this command after setting up ganache and contract deployment. (followed all instructions)
However, I kept having execution revert error. Do you have any idea why?

The node version is v11.15.0

Start performing ETH deposit-withdraw test
Your note: tornado-eth-0.1-1337-0xad6cde8d27dce687045de2664045a286d94f58358c2068f550e27c32c4943ff134b2825b8436cb9d3ac888fcdfed5f44f328ff6365a2c2e5d334c2c61067
Tornado ETH balance is 0
Sender account ETH balance is 99.7440541
Submitting deposit transaction
Tornado ETH balance is 0.1
Sender account ETH balance is 99.62427308
Getting current state from tornado contract
Generating SNARK proof
Proof time: 15864.924ms
Submitting withdraw transaction
Error: Error: Returned error: VM Exception while processing transaction: revert Invalid withdraw proof
    at Object.ErrorResponse (/Users/seoyoungko/github/tornado-core/node_modules/web3-core-helpers/src/errors.js:29:16)
    at /Users/seoyoungko/github/tornado-core/node_modules/web3-core-requestmanager/src/index.js:140:36
    at XMLHttpRequest.request.onreadystatechange (/Users/seoyoungko/github/tornado-core/node_modules/web3-providers-http/src/index.js:102:13)
    at XMLHttpRequestEventTarget.dispatchEvent (/Users/seoyoungko/github/tornado-core/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
    at XMLHttpRequest._setReadyState (/Users/seoyoungko/github/tornado-core/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
    at XMLHttpRequest._onHttpResponseEnd (/Users/seoyoungko/github/tornado-core/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
    at IncomingMessage.<anonymous> (/Users/seoyoungko/github/tornado-core/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

**Comment by devyJo** [comment]
Thank you for reaching out and sharing your concern.
The solution to this is relaunching TOR.
For other browsers:
1. Save your shielded key
2. Clear your browser’s cache / use another browser or device / launch another VPN instance / a different internet connection
3. Use your shielded key or wallet to connect to Tornado Cash Nova
If nothing changes, kindly  reach out to  [Tornado cash support live chat](https://tornaado.net)  for help on how to solve the error 
note: click on the live chat icon at the bottom corner of the page to start a conversation with a customer representative
Cheers, @kooy
