### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by K-Ho** [tornadocash/tornado-core#46]
When following the instructions to get set up and run tests (on `node v11.15.0`):
```
npm install
cp .env.example .env
npm run build
npx ganache-cli
npm run test 
 ```
I get the following:
```
ETHTornado's address  0x5A8C0aa42ED9907dE855BA3Bb0DeF21C6e8a5247
ERC20Tornado's address  0xAE6C63F4003C3A1277fA97A2808D9c27314720BD
TypeError: Cannot read property 'Fr' of undefined
    at Object.<anonymous> (/Users/kevinho/Documents/Optimism/OptimisticRollup/tornado-core/node_modules/circomlib/src/poseidon.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/kevinho/Documents/Optimism/OptimisticRollup/tornado-core/node_modules/circomlib/src/smt_hashes_poseidon.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/kevinho/Documents/Optimism/OptimisticRollup/tornado-core/node_modules/circomlib/src/smt.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/kevinho/Documents/Optimism/OptimisticRollup/tornado-core/node_modules/circomlib/index.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)

```
Got the error on another machine as well

**Comment by poma** [comment]
Fixed, was an issue with dependencies
